// @generated by pi-protocol generate; DO NOT EDIT.
// contract-digest: sha256:fb94c08363058402ac9ce4a877cd1924d590854660ec3fd39f98713c477f5bb1
import type { ProtocolAgentExecutor, ProtocolHandler } from "@kybernetria/pi-protocol/core";

export const PROTOCOL_NODE_ID = "pi-search-extension" as const;
export const PROTOCOL_TARGETS = {
  web_search: "pi-search-extension.web_search",
  fetch_content: "pi-search-extension.fetch_content",
} as const;

export type ProtocolProvideName = "web_search" | "fetch_content";
export type ProtocolBinding = ProtocolHandler | ProtocolAgentExecutor;
export type ProtocolBindings = {
  "web_search": ProtocolBinding;
  "fetch_content": ProtocolBinding;
};

export type WebSearchInput = { max_results?: number; query: string; };
export type WebSearchOutput = { text: string; };
export type FetchContentInput = { max_chars?: number; url: string; };
export type FetchContentOutput = { text: string; };
